### ISSUE TITLE
Not working completely anymore?

### ISSUE THREAD

**Issue by jorisvdstraten** [decurus/TouchOSCxBitwig#1]
Hi decurus,

Thanks for sharing your script and touchosc template.
I got it partly working, because it only works for the first remote control. Do you perhaps know what is causing this issue or what information do you need to be able to track it?

**Comment by decurus** [comment]
Hi Joris
Thanks for your interest in this small project. Currently, I am unable to reproduce your problem. I have the latest version of Bitwig installed (4.4.8) albeit only the 16 Track version, but that should not make any difference. Everything works as I intended. 
While checking everything out, I realized I hadn't pushed my latest version, so I did just that. The first thing you could try is install that, although I highly doubt that this would fix the bug since it has only added features, not bug fixes.
To get down to the root of your problem, I need some Information: 
Firstly, I am not entirely sure what you mean by "the first remote control". Am I correct in assuming, you mean "only the first knob is working"? If so, that indeed is not how it is supposed to work.
What OS are you running?
Do you have other MIDI devices attached? The most important feature of this script is that it runs purely on MIDI to avoid having a complicated setup, so it is possible, that other devices may also use the channels.
Does Bitwig show any error messages? Usually, they pop up on the top right, but you can also check directly by clicking on "Show Studio IO Panel" in the bottom-right corner of Bitwig, then clicking the Button "show console for controller scripts" (I guess that's what it says, I have set Bitwig to a different language). On the window that shows up, go to "TouchOSC" and check for any red error messages.
The next thing you can do is check for errors in the TouchOSC script. Open TouchOSC on your external device and enter the editor mode (where you can move around all the elements). Then open the side panel (the three parallel lines on the top right) and then the console (again the three parallel lines, but now the ones with equal length. Who decided it was a good idea to use icons that are so similar??). The console pops up on the bottom. Click where it says "MIDI" and go through all the entries to see if you find any errors.
For now, that's all that comes to mind, I hope we can find any clues as to what's going on.

**Comment by jorisvdstraten** [comment]
Thanks for your quick reply, I will try to look into it tonight!

**Comment by jorisvdstraten** [comment]
I've downloaded the newer pushed version and opened it in the TouchOSC App on my Mac (MacOS Ventura 13.3 M1 cpu). When selecting TouchOSC as midi input/output with Generic TouchOSC controller it gives the following errors in the Bitwig script console:
`initializing
initialization done
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
on Parameter: 0 new value:  90
on Parameter: 1 new value:  64
on Parameter: 2 new value:  64`

**Comment by jorisvdstraten** [comment]
But it seems to work now!
Do you think it might has something to do when working with the Touch OSC Bridge ports?

**Comment by jorisvdstraten** [comment]
It is working now, I made a mistake with the Touch OSC setup, my bad!
Thanks for your great work!
